// GENERATED by contracts/scripts/generate-slicer.py (tragedy-labs monorepo) from contracts/schema/v1/slicer/*.json — do not edit; regenerate there.
#pragma once
#include <cstdint>
#include <optional>
#include <string>
#include <vector>
#include <nlohmann/json.hpp>

namespace tragedy::slicer::messages {

/// `https://schema.tragedylabs.net/v1/slicer/config.json`. The values of every setting a selection resolves to, box by box, as the engine will slice with them: the print box, the printer box and one filament box per tool. Each box is an instance of the generated settings schema for it (`slicer/settings/fff/*.json`), so the shell's settings pages are the generated uischemas over these values and a value a person changes goes back as an override in the same shape (`slice-request.overrides`).
struct Config
{
    /// One of: `fff`.
    std::string technology{};
    nlohmann::json print{};
    nlohmann::json printer{};
    /// One filament box per tool, in tool order.
    std::vector<nlohmann::json> filaments{};
};

inline void to_json(nlohmann::json& j, const Config& v)
{
    j = nlohmann::json::object();
    j["technology"] = v.technology;
    j["print"] = v.print;
    j["printer"] = v.printer;
    j["filaments"] = v.filaments;
}

inline void from_json(const nlohmann::json& j, Config& v)
{
    j.at("technology").get_to(v.technology);
    j.at("print").get_to(v.print);
    j.at("printer").get_to(v.printer);
    j.at("filaments").get_to(v.filaments);
}

/// `https://schema.tragedylabs.net/v1/slicer/engine.json`. Which engine the slicer service is running: the name and version of the upstream slicer and the fork commit it was built from. A G-code file, a preset listing and a settings schema all come from one engine commit; the shell compares this with the commit the contracts were generated from (`contracts/slicer/engine-settings.json`) so a stale schema is noticed at the first request, not when a setting is silently ignored (ADR 0032).
struct Engine
{
    /// The upstream engine — `PrusaSlicer`.
    std::string name{};
    /// The upstream engine's version string, as its `Version.hpp` states it.
    std::string version{};
    /// The fork's name — `tragedy-slicer`.
    std::string fork{};
    /// The fork commit the service was built from, the full hash. `services/slicer/engine.lock.json` names the one the contracts expect.
    std::string commit{};
    /// The preset vendors loaded at start, by id — `PrusaResearch`. Empty means no preset bundle was found, and nothing can be sliced until one is.
    std::optional<std::vector<std::string>> vendors;
};

inline void to_json(nlohmann::json& j, const Engine& v)
{
    j = nlohmann::json::object();
    j["name"] = v.name;
    j["version"] = v.version;
    j["fork"] = v.fork;
    j["commit"] = v.commit;
    if (v.vendors) j["vendors"] = *v.vendors;
}

inline void from_json(const nlohmann::json& j, Engine& v)
{
    j.at("name").get_to(v.name);
    j.at("version").get_to(v.version);
    j.at("fork").get_to(v.fork);
    j.at("commit").get_to(v.commit);
    if (auto it = j.find("vendors"); it != j.end() && !it->is_null()) v.vendors = it->get<std::vector<std::string>>();
}

/// (inline object)
struct ModelObject
{
    /// The object's name — the file name for an STL, the object's name for a 3MF.
    std::string name{};
    /// How many facets the object's meshes hold, summed over its volumes.
    std::int64_t triangles{};
    /// The object's extent along x, y and z, in the engine's millimetres, before any instance transform.
    std::vector<double> size{};
};

inline void to_json(nlohmann::json& j, const ModelObject& v)
{
    j = nlohmann::json::object();
    j["name"] = v.name;
    j["triangles"] = v.triangles;
    j["size"] = v.size;
}

inline void from_json(const nlohmann::json& j, ModelObject& v)
{
    j.at("name").get_to(v.name);
    j.at("triangles").get_to(v.triangles);
    j.at("size").get_to(v.size);
}

/// `https://schema.tragedylabs.net/v1/slicer/model.json`. A model file the service holds, uploaded from the plater or named by path, as a handle: what a slice request names instead of sending the bytes again (ADR 0022's rule that results and inputs are handles). The service read it with the engine's own loader, so what it reports about the objects is what the slicer will see — not the browser's parse of the same file.
struct Model
{
    /// The handle. Opaque, valid for this run of the service.
    std::string id{};
    /// The file name it was uploaded or loaded as — `benchy.stl`. Used for the G-code's name.
    std::string name{};
    /// The file's size.
    std::int64_t bytes{};
    /// The objects the engine found in the file, in its order. An STL holds one; a 3MF may hold several.
    std::vector<ModelObject> objects{};
};

inline void to_json(nlohmann::json& j, const Model& v)
{
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["name"] = v.name;
    j["bytes"] = v.bytes;
    j["objects"] = v.objects;
}

inline void from_json(const nlohmann::json& j, Model& v)
{
    j.at("id").get_to(v.id);
    j.at("name").get_to(v.name);
    j.at("bytes").get_to(v.bytes);
    j.at("objects").get_to(v.objects);
}

/// `https://schema.tragedylabs.net/v1/slicer/preset-selection.json`. Which presets a slice uses: a printer, a printer preset evaluated for it, a print preset, and a tool print preset and a material preset per tool. Ids come from `preset-choices`; nothing here is typed by hand.
struct PresetSelection
{
    /// The printer's id (`printer.json`).
    std::optional<std::string> printer;
    /// The printer preset's id — one of `preset-choices.printerPresets`.
    std::optional<std::string> printerPreset;
    /// The print preset's id — one of `preset-choices.prints`.
    std::optional<std::string> print;
    /// A tool print preset id per tool, in tool order. Shorter than the tool count means the rest keep their current value.
    std::optional<std::vector<std::string>> tools;
    /// A material (filament or resin) preset id per tool, in tool order; shorter means the rest keep their current value.
    std::optional<std::vector<std::string>> materials;
};

inline void to_json(nlohmann::json& j, const PresetSelection& v)
{
    j = nlohmann::json::object();
    if (v.printer) j["printer"] = *v.printer;
    if (v.printerPreset) j["printerPreset"] = *v.printerPreset;
    if (v.print) j["print"] = *v.print;
    if (v.tools) j["tools"] = *v.tools;
    if (v.materials) j["materials"] = *v.materials;
}

inline void from_json(const nlohmann::json& j, PresetSelection& v)
{
    if (auto it = j.find("printer"); it != j.end() && !it->is_null()) v.printer = it->get<std::string>();
    if (auto it = j.find("printerPreset"); it != j.end() && !it->is_null()) v.printerPreset = it->get<std::string>();
    if (auto it = j.find("print"); it != j.end() && !it->is_null()) v.print = it->get<std::string>();
    if (auto it = j.find("tools"); it != j.end() && !it->is_null()) v.tools = it->get<std::vector<std::string>>();
    if (auto it = j.find("materials"); it != j.end() && !it->is_null()) v.materials = it->get<std::vector<std::string>>();
}

/// (inline object)
struct PrinterTool
{
    /// The tool configuration's id.
    std::string id{};
    /// As the engine shows it — `0.4 mm nozzle`.
    std::string name{};
    /// The nozzle's diameter, when the tool configuration states it.
    std::optional<double> nozzleDiameter;
};

inline void to_json(nlohmann::json& j, const PrinterTool& v)
{
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["name"] = v.name;
    if (v.nozzleDiameter) j["nozzleDiameter"] = *v.nozzleDiameter;
}

inline void from_json(const nlohmann::json& j, PrinterTool& v)
{
    j.at("id").get_to(v.id);
    j.at("name").get_to(v.name);
    if (auto it = j.find("nozzleDiameter"); it != j.end() && !it->is_null()) v.nozzleDiameter = it->get<double>();
}

/// `https://schema.tragedylabs.net/v1/slicer/printer.json`. A printer the engine knows how to slice for: the engine's hardware configuration (a printer model with its tool heads and the nozzles in them), listed so a person can pick one. The engine evaluates printer, print and material presets against this configuration — which presets exist for a 0.25 mm nozzle differs from a 0.4 mm one — so it is the first thing a selection names, and the choices for everything else follow from it.
struct Printer
{
    /// The engine's hardware configuration id. Opaque, and good for one run of the service only: the engine makes these up when it loads the bundle (the presets' ids, by contrast, are written in the vendor's YAML and survive a restart). A client that reconnects lists again and chooses afresh; one that sends a remembered id is told it is unknown. Printers as equipment (ADR 0012) will give a printer a lasting id.
    std::string id{};
    /// As the engine shows it — `Original Prusa MK4S`.
    std::string name{};
    /// The vendor id the bundle names — `PrusaResearch`.
    std::string vendor{};
    /// `fff` extrudes; `sla` cures resin. Decides which settings boxes apply and which G-code or layer format a slice produces. One of: `fff`, `sla`.
    std::string technology{};
    /// The printer model's id — `MK4S`.
    std::string model{};
    /// The tool heads, in the engine's order; the length is the printer's tool count. A tool print preset and a material preset are chosen per tool.
    std::vector<PrinterTool> tools{};
};

inline void to_json(nlohmann::json& j, const Printer& v)
{
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["name"] = v.name;
    j["vendor"] = v.vendor;
    j["technology"] = v.technology;
    j["model"] = v.model;
    j["tools"] = v.tools;
}

inline void from_json(const nlohmann::json& j, Printer& v)
{
    j.at("id").get_to(v.id);
    j.at("name").get_to(v.name);
    j.at("vendor").get_to(v.vendor);
    j.at("technology").get_to(v.technology);
    j.at("model").get_to(v.model);
    j.at("tools").get_to(v.tools);
}

/// `https://schema.tragedylabs.net/v1/slicer/preset.json`. A preset as the engine lists it: one entry of a printer, print, tool or material list. The `id` is the engine's own identifier for the evaluated preset — stable across runs for a system preset, since it is written in the vendor's YAML — and is what a selection and a slice request name. The `name` is for people; two vendors may use the same name, so nothing keys on it.
struct Preset
{
    /// The engine's preset id. Opaque; copy it back into a selection, never derive anything from it.
    std::string id{};
    /// The preset's name as the engine shows it — `0.20mm QUALITY`, `Prusament PLA`.
    std::string name{};
    /// Where the preset comes from. `system` is the vendor bundle the engine ships; `user` is a preset saved in the engine's data directory and shared with the desktop app; `runtime` was loaded from a project file and lives only for this run. One of: `system`, `user`, `runtime`.
    std::string origin{};
};

inline void to_json(nlohmann::json& j, const Preset& v)
{
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["name"] = v.name;
    j["origin"] = v.origin;
}

inline void from_json(const nlohmann::json& j, Preset& v)
{
    j.at("id").get_to(v.id);
    j.at("name").get_to(v.name);
    j.at("origin").get_to(v.origin);
}

/// `https://schema.tragedylabs.net/v1/slicer/preset-choices.json`. What can be selected, given a selection: every printer, and for the selected printer the printer presets, the print presets, and per tool the tool print presets and the material presets the engine evaluates as valid. The lists depend on the selection because the engine's presets are conditional — a print preset exists for some nozzle diameters and not others — so the shell asks again after each change rather than filtering a flat list itself and getting the conditions wrong.
struct PresetChoices
{
    PresetSelection selection{};
    /// Every printer the loaded bundles describe.
    std::vector<Printer> printers{};
    /// The printer presets evaluated for `selection.printer`.
    std::vector<Preset> printerPresets{};
    /// The print presets valid for the selected printer and printer preset.
    std::vector<Preset> prints{};
    /// Per tool, in tool order, the tool print presets valid for the selection.
    std::vector<std::vector<Preset>> tools{};
    /// Per tool, in tool order, the material presets valid for the selection.
    std::vector<std::vector<Preset>> materials{};
};

inline void to_json(nlohmann::json& j, const PresetChoices& v)
{
    j = nlohmann::json::object();
    j["selection"] = v.selection;
    j["printers"] = v.printers;
    j["printerPresets"] = v.printerPresets;
    j["prints"] = v.prints;
    j["tools"] = v.tools;
    j["materials"] = v.materials;
}

inline void from_json(const nlohmann::json& j, PresetChoices& v)
{
    j.at("selection").get_to(v.selection);
    j.at("printers").get_to(v.printers);
    j.at("printerPresets").get_to(v.printerPresets);
    j.at("prints").get_to(v.prints);
    j.at("tools").get_to(v.tools);
    j.at("materials").get_to(v.materials);
}

/// `https://schema.tragedylabs.net/v1/slicer/slice-notice.json`. An error or a warning the engine raised about a slice: its code, as the engine's enumerator is spelt, the settings it concerns, and a sentence. The code is the stable part — the sentence is the engine's English — so a client that wants its own wording keys on the code.
struct SliceNotice
{
    /// The engine's `ErrorCode` or `WarningCode` enumerator — `LayerHeightTooLarge`, `SupportsTurnedOff`.
    std::string code{};
    std::string message{};
    /// The setting keys the notice names, so a settings page can mark them. Empty for a notice about the whole print.
    std::vector<std::string> settings{};
    /// The name of the object concerned, when the notice is about one.
    std::optional<std::string> object;
};

inline void to_json(nlohmann::json& j, const SliceNotice& v)
{
    j = nlohmann::json::object();
    j["code"] = v.code;
    j["message"] = v.message;
    j["settings"] = v.settings;
    if (v.object) j["object"] = *v.object;
}

inline void from_json(const nlohmann::json& j, SliceNotice& v)
{
    j.at("code").get_to(v.code);
    j.at("message").get_to(v.message);
    j.at("settings").get_to(v.settings);
    if (auto it = j.find("object"); it != j.end() && !it->is_null()) v.object = it->get<std::string>();
}

/// What to slice: a handle from an upload, or a file path. One of the two, never both.
struct SliceRequestModel
{
    /// A model handle (`model.json`).
    std::optional<std::string> id;
    /// An absolute path of an STL, OBJ or 3MF file the service can read.
    std::optional<std::string> path;
};

inline void to_json(nlohmann::json& j, const SliceRequestModel& v)
{
    j = nlohmann::json::object();
    if (v.id) j["id"] = *v.id;
    if (v.path) j["path"] = *v.path;
}

inline void from_json(const nlohmann::json& j, SliceRequestModel& v)
{
    if (auto it = j.find("id"); it != j.end() && !it->is_null()) v.id = it->get<std::string>();
    if (auto it = j.find("path"); it != j.end() && !it->is_null()) v.path = it->get<std::string>();
}

/// Settings to change for this slice, by box. A key the box does not have, or a value the engine cannot parse, fails the request before anything is sliced, with the key named — a silently ignored override is a print with the wrong settings.
struct SliceRequestOverrides
{
    std::optional<nlohmann::json> print;
    std::optional<nlohmann::json> printer;
    /// Per tool, in tool order; an empty object leaves a tool's filament as selected.
    std::optional<std::vector<nlohmann::json>> filaments;
};

inline void to_json(nlohmann::json& j, const SliceRequestOverrides& v)
{
    j = nlohmann::json::object();
    if (v.print) j["print"] = *v.print;
    if (v.printer) j["printer"] = *v.printer;
    if (v.filaments) j["filaments"] = *v.filaments;
}

inline void from_json(const nlohmann::json& j, SliceRequestOverrides& v)
{
    if (auto it = j.find("print"); it != j.end() && !it->is_null()) v.print = it->get<nlohmann::json>();
    if (auto it = j.find("printer"); it != j.end() && !it->is_null()) v.printer = it->get<nlohmann::json>();
    if (auto it = j.find("filaments"); it != j.end() && !it->is_null()) v.filaments = it->get<std::vector<nlohmann::json>>();
}

/// `https://schema.tragedylabs.net/v1/slicer/slice-request.json`. Slice a model with a preset selection and optional overrides, to G-code. The model is a handle (`model.json`) or a path the service can read — the path form is for an agent or a script running an operation on a local file (ADR 0022), the handle for the plater that uploaded the file. Exactly one of the two is given.
struct SliceRequest
{
    /// What to slice: a handle from an upload, or a file path. One of the two, never both.
    SliceRequestModel model{};
    std::optional<PresetSelection> selection;
    /// Settings to change for this slice, by box. A key the box does not have, or a value the engine cannot parse, fails the request before anything is sliced, with the key named — a silently ignored override is a print with the wrong settings.
    std::optional<SliceRequestOverrides> overrides;
    /// Centre the objects on the bed before slicing, as the engine's CLI does. Off means the objects are sliced where the file puts them, which is what a 3MF project means and what an STL rarely does.
    bool arrange{true};
    /// Where to write the G-code, for a request made by path. Without it the G-code is kept by the service and fetched by `slice.result.gcode.url`.
    std::optional<std::string> output;
};

inline void to_json(nlohmann::json& j, const SliceRequest& v)
{
    j = nlohmann::json::object();
    j["model"] = v.model;
    if (v.selection) j["selection"] = *v.selection;
    if (v.overrides) j["overrides"] = *v.overrides;
    j["arrange"] = v.arrange;
    if (v.output) j["output"] = *v.output;
}

inline void from_json(const nlohmann::json& j, SliceRequest& v)
{
    j.at("model").get_to(v.model);
    if (auto it = j.find("selection"); it != j.end() && !it->is_null()) v.selection = it->get<PresetSelection>();
    if (auto it = j.find("overrides"); it != j.end() && !it->is_null()) v.overrides = it->get<SliceRequestOverrides>();
    if (auto it = j.find("arrange"); it != j.end() && !it->is_null()) it->get_to(v.arrange);
    if (auto it = j.find("output"); it != j.end() && !it->is_null()) v.output = it->get<std::string>();
}

/// How far the engine is, while running.
struct SliceProgress
{
    double percent{};
    /// The engine's name for the stage — `GeneratingPerimeters`, `MakingInfill`, `GeneratingGCode` — exactly as its `ProgressInfo` enumerator is spelt, so a label table keys on it.
    std::string stage{};
};

inline void to_json(nlohmann::json& j, const SliceProgress& v)
{
    j = nlohmann::json::object();
    j["percent"] = v.percent;
    j["stage"] = v.stage;
}

inline void from_json(const nlohmann::json& j, SliceProgress& v)
{
    j.at("percent").get_to(v.percent);
    j.at("stage").get_to(v.stage);
}

/// (inline object)
struct SliceResultGcode
{
    /// Where to fetch the G-code, relative to the service's base URL.
    std::string url{};
    /// Where it was written, when the request asked for a file.
    std::optional<std::string> path;
    std::int64_t bytes{};
    /// True when the printer preset asks for binary G-code (`.bgcode`); the browser preview in step 3 reads only text.
    bool binary{};
};

inline void to_json(nlohmann::json& j, const SliceResultGcode& v)
{
    j = nlohmann::json::object();
    j["url"] = v.url;
    if (v.path) j["path"] = *v.path;
    j["bytes"] = v.bytes;
    j["binary"] = v.binary;
}

inline void from_json(const nlohmann::json& j, SliceResultGcode& v)
{
    j.at("url").get_to(v.url);
    if (auto it = j.find("path"); it != j.end() && !it->is_null()) v.path = it->get<std::string>();
    j.at("bytes").get_to(v.bytes);
    j.at("binary").get_to(v.binary);
}

/// The engine's estimate for the print, from its G-code processor.
struct SliceResultStatistics
{
    /// Estimated print time in normal mode.
    double printTime{};
    double filamentLength{};
    /// In cubic centimetres, as the engine reports it; no vocabulary unit yet.
    double filamentVolume{};
    double filamentWeight{};
    /// In the currency the filament preset's cost is written in.
    double filamentCost{};
};

inline void to_json(nlohmann::json& j, const SliceResultStatistics& v)
{
    j = nlohmann::json::object();
    j["printTime"] = v.printTime;
    j["filamentLength"] = v.filamentLength;
    j["filamentVolume"] = v.filamentVolume;
    j["filamentWeight"] = v.filamentWeight;
    j["filamentCost"] = v.filamentCost;
}

inline void from_json(const nlohmann::json& j, SliceResultStatistics& v)
{
    j.at("printTime").get_to(v.printTime);
    j.at("filamentLength").get_to(v.filamentLength);
    j.at("filamentVolume").get_to(v.filamentVolume);
    j.at("filamentWeight").get_to(v.filamentWeight);
    j.at("filamentCost").get_to(v.filamentCost);
}

/// Present when `finished`.
struct SliceResult
{
    SliceResultGcode gcode{};
    /// The engine's estimate for the print, from its G-code processor.
    SliceResultStatistics statistics{};
};

inline void to_json(nlohmann::json& j, const SliceResult& v)
{
    j = nlohmann::json::object();
    j["gcode"] = v.gcode;
    j["statistics"] = v.statistics;
}

inline void from_json(const nlohmann::json& j, SliceResult& v)
{
    j.at("gcode").get_to(v.gcode);
    j.at("statistics").get_to(v.statistics);
}

/// `https://schema.tragedylabs.net/v1/slicer/slice.json`. A slicing job from request to result: what is being sliced, how far it is, and when it is done the G-code as a handle with the engine's statistics. The same message is the answer to a request, to a status query, and the event pushed on the service's WebSocket on every change, so a client has one shape to read.
struct Slice
{
    /// The job's handle. Opaque, valid for this run of the service.
    std::string id{};
    /// One of: `queued`, `running`, `finished`, `failed`, `cancelled`.
    std::string status{};
    Model model{};
    PresetSelection selection{};
    /// How far the engine is, while running.
    std::optional<SliceProgress> progress;
    /// Present when `finished`.
    std::optional<SliceResult> result;
    std::vector<SliceNotice> warnings{};
    std::vector<SliceNotice> errors{};
};

inline void to_json(nlohmann::json& j, const Slice& v)
{
    j = nlohmann::json::object();
    j["id"] = v.id;
    j["status"] = v.status;
    j["model"] = v.model;
    j["selection"] = v.selection;
    if (v.progress) j["progress"] = *v.progress;
    if (v.result) j["result"] = *v.result;
    j["warnings"] = v.warnings;
    j["errors"] = v.errors;
}

inline void from_json(const nlohmann::json& j, Slice& v)
{
    j.at("id").get_to(v.id);
    j.at("status").get_to(v.status);
    j.at("model").get_to(v.model);
    j.at("selection").get_to(v.selection);
    if (auto it = j.find("progress"); it != j.end() && !it->is_null()) v.progress = it->get<SliceProgress>();
    if (auto it = j.find("result"); it != j.end() && !it->is_null()) v.result = it->get<SliceResult>();
    j.at("warnings").get_to(v.warnings);
    j.at("errors").get_to(v.errors);
}

} // namespace tragedy::slicer::messages
